name: Build Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v5

      - name: Build all formats
        run: |
          mkdir dist
          for file in *.typ; do
            for fmt in pdf svg png; do
              typst compile "$file" "dist/$file.$fmt"
            done
          done

      - name: Generate tag name
        id: tag
        run: echo "name=$(date +'%m%d%Y%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          name: "Resume"
          tag: ${{ steps.tag.outputs.name }}
          commit: main
