name: Build Resume

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install reumes
        run: |
          git clone https://github.com/4jamesccraven/reumes.git
          cd reumes
          go build -o /usr/local/bin/reumes
          cd ..

      - name: Install Typst
        uses: typst-community/setup-typst@v4

      - name: Build Resume
        run: |
          reumes ./resume.yml -t pdf
          reumes ./resume.yml -t markdown

      - name: Create Tag Name
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'MMDDYYYYHHmmss'

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./Resume.pdf,./Resume.md"
          name: "Resume"
          tag: "${{ steps.time.outputs.time }}"
